"""Cost-aware Hunter scheduling contracts and metrics."""

from .budget import (
    AdmissionDecision,
    AdmissionEvent,
    AdmissionRankingRecord,
    BudgetAllocation,
    BudgetController,
    BudgetedLLMClient,
    BudgetExceededError,
    CAPACITY_ADMISSION_UNIT_POLICY,
    CapacityAdmissionUnit,
    NATIVE_DIVERSE_POLICY,
    HUNTER_INPUT_SOFT_STOP,
    ObligationAdmissionRecord,
    RecyclableAdmissionLedger,
    WORK_INPUT_FAIRNESS_POLICY,
    WorkInputBudgetPlan,
    adaptive_iteration_limit,
    adaptive_output_token_limit,
    allocate_work_items,
    apply_admission_focus,
    build_work_input_budget,
)
from .metrics import estimate_cost_usd, total_usage
from .profiles import (
    CUSTOM_PROFILE,
    DEEP_16,
    DEEP_16_PROFILE,
    HUNTER_BUDGET_PROFILE_NAMES,
    STANDARD_12,
    STANDARD_12_PROFILE,
    STANDARD_SESSION_BOUNDARY,
    budget_profile_artifact,
    hunter_budget_profile,
    resolve_hunter_budget_config,
)
from .planning import (
    NATIVE_PLAN_CONTRACT_POLICY,
    NativeAdmissionPlan,
    NativeWorkPlan,
    allocate_native_work_plan,
    build_native_work_plan,
)
from .router import ROUTER_POLICY, build_routing_plan
from .obligations import (
    OBLIGATION_ADMISSION_POLICY,
    bind_invariant_obligations,
    supported_invariant_obligations,
)
from .shadow import build_shadow_plan, work_id_for
from .slices import (
    MAX_CONTEXT_FILES,
    SLICE_WORK_POLICY,
    build_slice_work_items,
    group_overlapping_slices,
)

__all__ = [
    "AdmissionDecision",
    "AdmissionEvent",
    "AdmissionRankingRecord",
    "BudgetAllocation",
    "BudgetController",
    "BudgetedLLMClient",
    "BudgetExceededError",
    "CUSTOM_PROFILE",
    "CAPACITY_ADMISSION_UNIT_POLICY",
    "CapacityAdmissionUnit",
    "DEEP_16",
    "DEEP_16_PROFILE",
    "HUNTER_BUDGET_PROFILE_NAMES",
    "NATIVE_DIVERSE_POLICY",
    "HUNTER_INPUT_SOFT_STOP",
    "NATIVE_PLAN_CONTRACT_POLICY",
    "OBLIGATION_ADMISSION_POLICY",
    "NativeAdmissionPlan",
    "NativeWorkPlan",
    "ObligationAdmissionRecord",
    "RecyclableAdmissionLedger",
    "WORK_INPUT_FAIRNESS_POLICY",
    "WorkInputBudgetPlan",
    "ROUTER_POLICY",
    "MAX_CONTEXT_FILES",
    "SLICE_WORK_POLICY",
    "STANDARD_12",
    "STANDARD_12_PROFILE",
    "STANDARD_SESSION_BOUNDARY",
    "adaptive_iteration_limit",
    "adaptive_output_token_limit",
    "allocate_work_items",
    "allocate_native_work_plan",
    "apply_admission_focus",
    "build_work_input_budget",
    "budget_profile_artifact",
    "build_slice_work_items",
    "build_native_work_plan",
    "bind_invariant_obligations",
    "build_routing_plan",
    "build_shadow_plan",
    "estimate_cost_usd",
    "group_overlapping_slices",
    "hunter_budget_profile",
    "resolve_hunter_budget_config",
    "total_usage",
    "supported_invariant_obligations",
    "work_id_for",
]
