"""macOS-specific discovery control-plane support."""

from .imageio_crashes import (
    ImageIOCrashHunterPlan,
    ImageIOCrashTriageClass,
    build_imageio_crash_hunter_plan,
    cluster_imageio_crashes,
    load_imageio_crash_observations,
    minimize_imageio_crash,
)
from .imageio_fuzzer import (
    ImageIODecodeStage,
    ImageIOFuzzBudget,
    ImageIOFuzzCampaignSummary,
    ImageIOSeedQualification,
    PrivateImageIOFuzzStore,
    PrivateImageIOPayloadHistory,
    build_minimal_dicom_seed,
    generate_dicom_fuzz_cases,
    run_imageio_fuzz_campaign,
)
from .imageio_disclosure import (
    ImageIODisclosureAssessment,
    ImageIODisclosureOracleStatus,
    ImageIORawPixelObservation,
    assess_canary_disclosure,
    normalize_raw_pixel_observation,
)
from .imageio_fuzz_benchmark import (
    ImageIOFuzzBenchmarkAssessment,
    ImageIOFuzzBenchmarkStatus,
    assess_imageio_fuzz_benchmark,
)
from .imageio_inventory import (
    FrozenImageIOCampaign,
    ImageIOAPIRoute,
    ImageIOCampaignManifest,
    ImageIOFormatFamily,
    ImageIOInventory,
    assess_campaign_readiness,
    capture_imageio_inventory,
    freeze_campaign_manifest,
    write_frozen_campaign,
)
from .imageio_hunter import (
    ImageIOBinaryContext,
    ImageIOExperimentPlan,
    ImageIOExperimentPlanStatus,
    ImageIOExperimentReview,
    ImageIOHunterAssessment,
    ImageIOHunterPacket,
    build_imageio_hunter_packet,
    execute_imageio_hunter_plan,
    plan_imageio_experiments,
    review_imageio_experiment,
)
from .imageio_harness import ImageIOCanaryInterposer
from .imageio_sgi import (
    GeneratedImageIOSGICase,
    ImageIOSGIMutationCase,
    ImageIOSGIQualificationObservation,
    ImageIOSGIRelation,
    ImageIOSGIRowRange,
    ImageIOSGISeedLayout,
    ImageIOSGISeedQualification,
    build_minimal_sgi_rle_seed,
    generate_sgi_relational_cases,
    parse_sgi_rle_seed,
    qualify_sgi_seed,
)

__all__ = [
    "FrozenImageIOCampaign",
    "ImageIOAPIRoute",
    "ImageIOBinaryContext",
    "ImageIOCampaignManifest",
    "ImageIOCanaryInterposer",
    "ImageIOCrashHunterPlan",
    "ImageIOCrashTriageClass",
    "ImageIODecodeStage",
    "ImageIODisclosureAssessment",
    "ImageIODisclosureOracleStatus",
    "ImageIOFuzzBudget",
    "ImageIOFuzzBenchmarkAssessment",
    "ImageIOFuzzBenchmarkStatus",
    "ImageIOFuzzCampaignSummary",
    "ImageIOFormatFamily",
    "ImageIOInventory",
    "ImageIORawPixelObservation",
    "ImageIOSeedQualification",
    "ImageIOSGIMutationCase",
    "ImageIOSGIQualificationObservation",
    "ImageIOSGIRelation",
    "ImageIOSGIRowRange",
    "ImageIOSGISeedLayout",
    "ImageIOSGISeedQualification",
    "ImageIOExperimentPlan",
    "ImageIOExperimentPlanStatus",
    "ImageIOExperimentReview",
    "ImageIOHunterAssessment",
    "ImageIOHunterPacket",
    "PrivateImageIOFuzzStore",
    "PrivateImageIOPayloadHistory",
    "GeneratedImageIOSGICase",
    "assess_campaign_readiness",
    "assess_canary_disclosure",
    "assess_imageio_fuzz_benchmark",
    "build_minimal_dicom_seed",
    "build_minimal_sgi_rle_seed",
    "build_imageio_hunter_packet",
    "build_imageio_crash_hunter_plan",
    "capture_imageio_inventory",
    "cluster_imageio_crashes",
    "freeze_campaign_manifest",
    "generate_dicom_fuzz_cases",
    "generate_sgi_relational_cases",
    "load_imageio_crash_observations",
    "minimize_imageio_crash",
    "normalize_raw_pixel_observation",
    "parse_sgi_rle_seed",
    "run_imageio_fuzz_campaign",
    "execute_imageio_hunter_plan",
    "plan_imageio_experiments",
    "qualify_sgi_seed",
    "review_imageio_experiment",
    "write_frozen_campaign",
]
