"""Deterministic analysis graphs, coverage plans, and Hunter context."""

from .c_graph import build_c_analysis_graph
from .capacity import (
    CAPACITY_FACT_POLICY,
    MAX_ALIAS_HOPS,
    MAX_CAPACITY_TRANSFORMS,
    extract_capacity_facts,
)
from .capacity_summaries import (
    CAPACITY_SUMMARY_POLICY,
    MAX_CAPACITY_CALL_DEPTH,
    propagate_capacity_summaries,
)
from .capacity_chains import (
    CAPACITY_RISK_CHAIN_POLICY,
    build_capacity_risk_chains,
)
from .context import context_for_file, context_for_work_item
from .context_cache import (
    CONTEXT_CACHE_POLICY,
    CONTEXT_SHARD_POLICY,
    SharedContextCache,
    context_cache_key,
)
from .constraints import CONSTRAINT_POLICY, extract_constraint_facts
from .cursor import (
    CURSOR_ACCESS_POLICY,
    CURSOR_TRANSITION_POLICY,
    build_cursor_transition_chains,
    extract_cursor_facts,
    extract_cursor_macros,
)
from .incremental import INCREMENTAL_POLICY, build_incremental_scope
from .formatted_output import FORMATTED_OUTPUT_POLICY, extract_formatted_output_facts
from .scope import SCAN_SCOPE_POLICY, build_scan_scope
from .models import (
    AnalysisSlice,
    CAnalysisGraph,
    CapacityFact,
    CapacityFactKind,
    CapacityCallSite,
    CapacityPriorityClass,
    CapacityRiskChain,
    CapacityReturnKind,
    ConstraintFact,
    ConstraintKind,
    CursorFact,
    CursorFactKind,
    CursorTransitionChain,
    CoveragePlan,
    EdgeKind,
    GraphEdge,
    GraphNode,
    FunctionCapacitySummary,
    FormattedDestinationKind,
    FormattedExpansionClass,
    FormattedOutputFact,
    GuardState,
    InvariantClosureState,
    InvariantObligation,
    InvariantObligationDisposition,
    InvariantObligationKind,
    IncrementalScope,
    NodeKind,
    ObligationEvidenceRange,
    RiskChain,
    RiskTransform,
    SecuritySignal,
    SignalRole,
)
from .obligations import INVARIANT_OBLIGATION_POLICY, build_invariant_obligations
from .planner import build_coverage_plan
from .risk_chains import RISK_CHAIN_POLICY

__all__ = [
    "AnalysisSlice",
    "CAnalysisGraph",
    "CapacityFact",
    "CapacityFactKind",
    "CapacityCallSite",
    "CapacityPriorityClass",
    "CapacityRiskChain",
    "CapacityReturnKind",
    "ConstraintFact",
    "ConstraintKind",
    "CursorFact",
    "CursorFactKind",
    "CursorTransitionChain",
    "CoveragePlan",
    "EdgeKind",
    "GraphEdge",
    "GraphNode",
    "FunctionCapacitySummary",
    "FormattedDestinationKind",
    "FormattedExpansionClass",
    "FormattedOutputFact",
    "GuardState",
    "InvariantClosureState",
    "InvariantObligation",
    "InvariantObligationDisposition",
    "InvariantObligationKind",
    "IncrementalScope",
    "NodeKind",
    "ObligationEvidenceRange",
    "RiskChain",
    "RiskTransform",
    "SecuritySignal",
    "SignalRole",
    "RISK_CHAIN_POLICY",
    "INVARIANT_OBLIGATION_POLICY",
    "build_invariant_obligations",
    "FORMATTED_OUTPUT_POLICY",
    "extract_formatted_output_facts",
    "build_c_analysis_graph",
    "build_coverage_plan",
    "context_for_file",
    "context_for_work_item",
    "CONTEXT_CACHE_POLICY",
    "CONTEXT_SHARD_POLICY",
    "CONSTRAINT_POLICY",
    "SharedContextCache",
    "INCREMENTAL_POLICY",
    "SCAN_SCOPE_POLICY",
    "build_incremental_scope",
    "build_scan_scope",
    "context_cache_key",
    "extract_constraint_facts",
    "CURSOR_ACCESS_POLICY",
    "CURSOR_TRANSITION_POLICY",
    "extract_cursor_macros",
    "extract_cursor_facts",
    "build_cursor_transition_chains",
    "CAPACITY_FACT_POLICY",
    "MAX_ALIAS_HOPS",
    "MAX_CAPACITY_TRANSFORMS",
    "extract_capacity_facts",
    "CAPACITY_SUMMARY_POLICY",
    "MAX_CAPACITY_CALL_DEPTH",
    "propagate_capacity_summaries",
    "CAPACITY_RISK_CHAIN_POLICY",
    "build_capacity_risk_chains",
]
